import { SYSTEM_ROLES, type SystemRole } from '@/entities/user'
import { Permission } from './permissions'

const MARKETPLACE_PERMISSIONS: Permission[] = [
  Permission.VIEW_OPPORTUNITIES,
  Permission.CREATE_OPPORTUNITY,
  Permission.CREATE_PROPOSAL,
  Permission.MANAGE_SHORTLIST,
  Permission.START_NEGOTIATION,
  Permission.VIEW_COMPANY_PROFILE,
  Permission.MANAGE_FAVORITES,
  Permission.VIEW_NOTIFICATIONS,
  Permission.VIEW_COMPANY,
]

const COMPANY_MANAGE_PERMISSIONS: Permission[] = [
  Permission.EDIT_COMPANY,
  Permission.MANAGE_COMPANY_MEMBERS,
  Permission.INVITE_COMPANY_MEMBER,
  Permission.CHANGE_MEMBER_ROLE,
  Permission.REMOVE_COMPANY_MEMBER,
  Permission.MANAGE_COMPANY_SERVICES,
  Permission.MANAGE_COMPANY_CASES,
  Permission.MANAGE_COMPANY_DOCUMENTS,
  Permission.MANAGE_COMPANY_PERMISSIONS,
  Permission.VIEW_COMPANY_PERMISSIONS,
  Permission.MANAGE_COMPANY_SETTINGS,
  Permission.VIEW_COMPANY_VERIFICATION,
  Permission.VIEW_COMPANY_ACTIVITY,
]

const MODERATION_PERMISSIONS: Permission[] = [
  Permission.VIEW_MODERATION,
  Permission.MANAGE_MODERATION,
  Permission.MODERATE_COMPANIES,
  Permission.MODERATE_OPPORTUNITIES,
  Permission.MODERATE_DOCUMENTS,
  Permission.HANDLE_REPORTS,
  Permission.VIEW_MODERATION_DASHBOARD,
  Permission.VIEW_MODERATION_QUEUE,
  Permission.VIEW_MODERATION_ITEM,
  Permission.APPROVE_MODERATION_ITEM,
  Permission.REJECT_MODERATION_ITEM,
  Permission.REQUEST_MODERATION_CHANGES,
  Permission.BLOCK_MODERATION_ITEM,
  Permission.VIEW_REPORTS,
  Permission.ESCALATE_REPORT,
  Permission.VIEW_MODERATION_HISTORY,
  Permission.VIEW_ESCALATIONS,
]

const PLATFORM_ADMIN_PERMISSIONS: Permission[] = [
  Permission.VIEW_ADMIN_DASHBOARD,
  Permission.VIEW_USERS,
  Permission.MANAGE_USERS,
  Permission.BLOCK_USER,
  Permission.CHANGE_USER_SYSTEM_ROLE,
  Permission.VIEW_COMPANIES,
  Permission.MANAGE_COMPANY_PLATFORM_STATUS,
  Permission.CHANGE_COMPANY_VERIFICATION,
  Permission.VIEW_DICTIONARIES,
  Permission.MANAGE_DICTIONARIES,
  Permission.VIEW_ANALYTICS,
  Permission.VIEW_AUDIT_LOG,
  Permission.VIEW_PLATFORM_SETTINGS,
  Permission.MANAGE_PLATFORM_SETTINGS,
  Permission.VIEW_FEATURE_FLAGS,
  Permission.MANAGE_FEATURE_FLAGS,
  Permission.VIEW_SYSTEM_NOTIFICATIONS,
]

export const ROLE_PERMISSIONS: Record<SystemRole, Permission[]> = {
  [SYSTEM_ROLES.BUSINESS_USER]: [...MARKETPLACE_PERMISSIONS],
  [SYSTEM_ROLES.COMPANY_ADMIN]: [...MARKETPLACE_PERMISSIONS, ...COMPANY_MANAGE_PERMISSIONS],
  [SYSTEM_ROLES.MODERATOR]: [...MODERATION_PERMISSIONS],
  [SYSTEM_ROLES.PLATFORM_ADMIN]: [
    ...MODERATION_PERMISSIONS,
    ...PLATFORM_ADMIN_PERMISSIONS,
  ],
}
