import { SYSTEM_ROLES, type SystemRole } from '@/entities/user'
import { Permission } from './permissions'

const MARKETPLACE_PERMISSIONS: Permission[] = [
  Permission.VIEW_OPPORTUNITIES,
  Permission.CREATE_OPPORTUNITY,
  Permission.CREATE_PROPOSAL,
  Permission.MANAGE_SHORTLIST,
  Permission.START_NEGOTIATION,
  Permission.VIEW_COMPANY_PROFILE,
  Permission.MANAGE_FAVORITES,
  Permission.VIEW_NOTIFICATIONS,
  Permission.VIEW_COMPANY,
]

const COMPANY_MANAGE_PERMISSIONS: Permission[] = [
  Permission.EDIT_COMPANY,
  Permission.MANAGE_COMPANY_MEMBERS,
  Permission.INVITE_COMPANY_MEMBER,
  Permission.CHANGE_MEMBER_ROLE,
  Permission.REMOVE_COMPANY_MEMBER,
  Permission.MANAGE_COMPANY_SERVICES,
  Permission.MANAGE_COMPANY_CASES,
  Permission.MANAGE_COMPANY_DOCUMENTS,
  Permission.MANAGE_COMPANY_PERMISSIONS,
  Permission.VIEW_COMPANY_PERMISSIONS,
  Permission.MANAGE_COMPANY_SETTINGS,
  Permission.VIEW_COMPANY_VERIFICATION,
  Permission.VIEW_COMPANY_ACTIVITY,
]

const MODERATION_PERMISSIONS: Permission[] = [
  Permission.VIEW_MODERATION,
  Permission.MODERATE_COMPANIES,
  Permission.MODERATE_OPPORTUNITIES,
  Permission.MODERATE_DOCUMENTS,
  Permission.HANDLE_REPORTS,
]

const PLATFORM_ADMIN_PERMISSIONS: Permission[] = [
  Permission.MANAGE_PLATFORM_USERS,
  Permission.MANAGE_PLATFORM_COMPANIES,
  Permission.MANAGE_DICTIONARIES,
  Permission.VIEW_PLATFORM_ANALYTICS,
  Permission.MANAGE_PLATFORM_SETTINGS,
  Permission.VIEW_ADMIN_DASHBOARD,
]

export const ROLE_PERMISSIONS: Record<SystemRole, Permission[]> = {
  [SYSTEM_ROLES.BUSINESS_USER]: [...MARKETPLACE_PERMISSIONS],
  [SYSTEM_ROLES.COMPANY_ADMIN]: [...MARKETPLACE_PERMISSIONS, ...COMPANY_MANAGE_PERMISSIONS],
  [SYSTEM_ROLES.MODERATOR]: [...MODERATION_PERMISSIONS],
  [SYSTEM_ROLES.PLATFORM_ADMIN]: [
    ...MARKETPLACE_PERMISSIONS,
    ...COMPANY_MANAGE_PERMISSIONS,
    ...MODERATION_PERMISSIONS,
    ...PLATFORM_ADMIN_PERMISSIONS,
  ],
}
