export const COMPANY_ACTIVITY_TYPE = {
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  MEMBER_INVITED: 'MEMBER_INVITED',
  MEMBER_ROLE_CHANGED: 'MEMBER_ROLE_CHANGED',
  MEMBER_SUSPENDED: 'MEMBER_SUSPENDED',
  MEMBER_REMOVED: 'MEMBER_REMOVED',
  SERVICE_CREATED: 'SERVICE_CREATED',
  SERVICE_UPDATED: 'SERVICE_UPDATED',
  SERVICE_ARCHIVED: 'SERVICE_ARCHIVED',
  SERVICE_HIDDEN: 'SERVICE_HIDDEN',
  CASE_CREATED: 'CASE_CREATED',
  CASE_UPDATED: 'CASE_UPDATED',
  CASE_ARCHIVED: 'CASE_ARCHIVED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_REMOVED: 'DOCUMENT_REMOVED',
  DOCUMENT_REPLACED: 'DOCUMENT_REPLACED',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
} as const

export type CompanyActivityType =
  (typeof COMPANY_ACTIVITY_TYPE)[keyof typeof COMPANY_ACTIVITY_TYPE]

export interface CompanyActivityEvent {
  id: string
  companyId: string
  type: CompanyActivityType
  actorName: string
  action: string
  entityLabel?: string
  createdAt: string
}
