"""Company-scoped RBAC mirroring frontend companyRolePermissions."""

from __future__ import annotations

from .roles import (
    MEMBER_ROLE_ADMIN,
    MEMBER_ROLE_MANAGER,
    MEMBER_ROLE_VIEWER,
    ROLE_BUSINESS_USER,
    ROLE_COMPANY_ADMIN,
    ROLE_MODERATOR,
    ROLE_PLATFORM_ADMIN,
)

# Permission keys (aligned with FE Permission enum)
PERM_VIEW_COMPANY_PROFILE = "VIEW_COMPANY_PROFILE"
PERM_EDIT_COMPANY = "EDIT_COMPANY"
PERM_MANAGE_COMPANY_MEMBERS = "MANAGE_COMPANY_MEMBERS"
PERM_INVITE_COMPANY_MEMBER = "INVITE_COMPANY_MEMBER"
PERM_CHANGE_MEMBER_ROLE = "CHANGE_MEMBER_ROLE"
PERM_REMOVE_COMPANY_MEMBER = "REMOVE_COMPANY_MEMBER"
PERM_MANAGE_COMPANY_SERVICES = "MANAGE_COMPANY_SERVICES"
PERM_MANAGE_COMPANY_CASES = "MANAGE_COMPANY_CASES"
PERM_MANAGE_COMPANY_DOCUMENTS = "MANAGE_COMPANY_DOCUMENTS"
PERM_VIEW_COMPANY_DOCUMENTS = "VIEW_COMPANY_DOCUMENTS"
PERM_MANAGE_COMPANY_SETTINGS = "MANAGE_COMPANY_SETTINGS"
PERM_VIEW_COMPANY_SERVICES = "VIEW_COMPANY_SERVICES"
PERM_VIEW_COMPANY_CASES = "VIEW_COMPANY_CASES"
PERM_VIEW_COMPANY_VERIFICATION = "VIEW_COMPANY_VERIFICATION"
PERM_VIEW_COMPANY_ACTIVITY = "VIEW_COMPANY_ACTIVITY"
PERM_CREATE_OPPORTUNITY = "CREATE_OPPORTUNITY"
PERM_CREATE_PROPOSAL = "CREATE_PROPOSAL"
PERM_MANAGE_SHORTLIST = "MANAGE_SHORTLIST"
PERM_START_NEGOTIATION = "START_NEGOTIATION"
PERM_VIEW_DEALS = "VIEW_DEALS"
PERM_VIEW_OPPORTUNITIES = "VIEW_OPPORTUNITIES"
PERM_MANAGE_FAVORITES = "MANAGE_FAVORITES"
PERM_VIEW_NOTIFICATIONS = "VIEW_NOTIFICATIONS"
PERM_VIEW_COMPANY = "VIEW_COMPANY"

_MARKETPLACE = {
    PERM_VIEW_OPPORTUNITIES,
    PERM_CREATE_OPPORTUNITY,
    PERM_CREATE_PROPOSAL,
    PERM_MANAGE_SHORTLIST,
    PERM_START_NEGOTIATION,
    PERM_VIEW_DEALS,
    PERM_VIEW_COMPANY_PROFILE,
    PERM_MANAGE_FAVORITES,
    PERM_VIEW_NOTIFICATIONS,
    PERM_VIEW_COMPANY,
}

_COMPANY_ADMIN_MANAGE = {
    PERM_EDIT_COMPANY,
    PERM_MANAGE_COMPANY_MEMBERS,
    PERM_INVITE_COMPANY_MEMBER,
    PERM_CHANGE_MEMBER_ROLE,
    PERM_REMOVE_COMPANY_MEMBER,
    PERM_MANAGE_COMPANY_SERVICES,
    PERM_MANAGE_COMPANY_CASES,
    PERM_MANAGE_COMPANY_DOCUMENTS,
    PERM_MANAGE_COMPANY_SETTINGS,
    PERM_VIEW_COMPANY_VERIFICATION,
    PERM_VIEW_COMPANY_ACTIVITY,
    PERM_VIEW_COMPANY_SERVICES,
    PERM_VIEW_COMPANY_CASES,
    PERM_VIEW_COMPANY_DOCUMENTS,
}

COMPANY_ROLE_PERMISSIONS: dict[str, set[str]] = {
    MEMBER_ROLE_ADMIN: _MARKETPLACE | _COMPANY_ADMIN_MANAGE,
    MEMBER_ROLE_MANAGER: {
        PERM_VIEW_OPPORTUNITIES,
        PERM_CREATE_OPPORTUNITY,
        PERM_CREATE_PROPOSAL,
        PERM_MANAGE_SHORTLIST,
        PERM_START_NEGOTIATION,
        PERM_VIEW_DEALS,
        PERM_MANAGE_FAVORITES,
        PERM_VIEW_NOTIFICATIONS,
        PERM_VIEW_COMPANY_PROFILE,
        PERM_VIEW_COMPANY,
        PERM_MANAGE_COMPANY_SERVICES,
        PERM_MANAGE_COMPANY_CASES,
        PERM_VIEW_COMPANY_SERVICES,
        PERM_VIEW_COMPANY_CASES,
        PERM_VIEW_COMPANY_DOCUMENTS,
        PERM_VIEW_COMPANY_VERIFICATION,
        PERM_VIEW_COMPANY_ACTIVITY,
    },
    MEMBER_ROLE_VIEWER: {
        PERM_VIEW_OPPORTUNITIES,
        PERM_VIEW_DEALS,
        PERM_VIEW_COMPANY_PROFILE,
        PERM_VIEW_COMPANY,
        PERM_VIEW_COMPANY_SERVICES,
        PERM_VIEW_COMPANY_CASES,
        PERM_VIEW_COMPANY_DOCUMENTS,
        PERM_VIEW_COMPANY_VERIFICATION,
        PERM_VIEW_COMPANY_ACTIVITY,
        PERM_VIEW_NOTIFICATIONS,
        PERM_MANAGE_FAVORITES,
    },
}

# BUSINESS_USER without company membership: marketplace only
BUSINESS_USER_PERMISSIONS = set(_MARKETPLACE)

# Platform roles that must not use marketplace company-manage APIs
STAFF_ROLES = {ROLE_PLATFORM_ADMIN, ROLE_MODERATOR}


def company_role_has_permission(member_role: str | None, permission: str) -> bool:
    if not member_role:
        return False
    return permission in COMPANY_ROLE_PERMISSIONS.get(member_role, set())
