"""Platform and company role constants aligned with frontend SYSTEM_ROLES / member roles."""

from __future__ import annotations

ROLE_BUSINESS_USER = "BUSINESS_USER"
ROLE_COMPANY_ADMIN = "COMPANY_ADMIN"
ROLE_MODERATOR = "MODERATOR"
ROLE_PLATFORM_ADMIN = "PLATFORM_ADMIN"

PLATFORM_ROLES = {
    ROLE_BUSINESS_USER,
    ROLE_COMPANY_ADMIN,
    ROLE_MODERATOR,
    ROLE_PLATFORM_ADMIN,
}

MEMBER_ROLE_ADMIN = "COMPANY_ADMIN"
MEMBER_ROLE_MANAGER = "MANAGER"
MEMBER_ROLE_VIEWER = "VIEWER"

MEMBER_ROLES = {MEMBER_ROLE_ADMIN, MEMBER_ROLE_MANAGER, MEMBER_ROLE_VIEWER}

MEMBER_STATUS_ACTIVE = "active"
MEMBER_STATUS_INVITED = "invited"
MEMBER_STATUS_SUSPENDED = "suspended"
MEMBER_STATUS_DEACTIVATED = "deactivated"

# Seed MAX user ids for demo roles
SEED_PLATFORM_ADMIN = 7777001
SEED_COMPANY_ADMIN = 7777002
SEED_BUSINESS_USER = 7777003
SEED_MODERATOR = 7777009
SEED_MANAGER = 7777010
SEED_VIEWER = 7777011
SEED_PENDING_INVITE_TOKEN = "demo-invite-pending-digitallab"  # known token for FE demo

# Invitation API status (mapped from CompanyMember.status)
INVITE_STATUS_PENDING = "pending"
INVITE_STATUS_ACCEPTED = "accepted"
INVITE_STATUS_DECLINED = "declined"
INVITE_STATUS_EXPIRED = "expired"
INVITE_STATUS_CANCELLED = "cancelled"

MEMBER_STATUS_DECLINED = "declined"

# Report enums aligned with FE REPORT_TYPE
REPORT_TYPES = {
    "SPAM",
    "FRAUD",
    "FAKE_COMPANY",
    "MISLEADING_INFORMATION",
    "INAPPROPRIATE_CONTENT",
    "DUPLICATE",
    "OTHER",
}
REPORT_TARGET_TYPES = {
    "company",
    "opportunity",
    "proposal",
    "case",
    "document",
    "user",
}
