from __future__ import annotations

SERVICE_STATUS_DRAFT = "draft"
SERVICE_STATUS_PUBLISHED = "published"
SERVICE_STATUS_HIDDEN = "hidden"
SERVICE_STATUS_ARCHIVED = "archived"

SERVICE_STATUSES = {
    SERVICE_STATUS_DRAFT,
    SERVICE_STATUS_PUBLISHED,
    SERVICE_STATUS_HIDDEN,
    SERVICE_STATUS_ARCHIVED,
}

PUBLIC_SERVICE_STATUS = SERVICE_STATUS_PUBLISHED

CASE_STATUS_DRAFT = "draft"
CASE_STATUS_PUBLISHED = "published"
CASE_STATUS_HIDDEN = "hidden"
CASE_STATUS_ARCHIVED = "archived"

CASE_STATUSES = {
    CASE_STATUS_DRAFT,
    CASE_STATUS_PUBLISHED,
    CASE_STATUS_HIDDEN,
    CASE_STATUS_ARCHIVED,
}

PUBLIC_CASE_STATUS = CASE_STATUS_PUBLISHED

_LEGACY_SERVICE_MAP = {
    "active": SERVICE_STATUS_PUBLISHED,
    "inactive": SERVICE_STATUS_ARCHIVED,
    "ACTIVE": SERVICE_STATUS_PUBLISHED,
    "DRAFT": SERVICE_STATUS_DRAFT,
    "PUBLISHED": SERVICE_STATUS_PUBLISHED,
    "HIDDEN": SERVICE_STATUS_HIDDEN,
    "ARCHIVED": SERVICE_STATUS_ARCHIVED,
}


def normalize_service_status(value: str) -> str:
    return _LEGACY_SERVICE_MAP.get(value, value)
